/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackSlugRouteImport } from './routes/track.$slug'
import { Route as RoadmapSystemDesignEngineerRouteImport } from './routes/roadmap.system-design-engineer'
import { Route as RoadmapSdeRouteImport } from './routes/roadmap.sde'
import { Route as RoadmapMlEngineerRouteImport } from './routes/roadmap.ml-engineer'
import { Route as RoadmapFullstackDeveloperRouteImport } from './routes/roadmap.fullstack-developer'
import { Route as RoadmapDataScientistRouteImport } from './routes/roadmap.data-scientist'
import { Route as RoadmapCyberSecurityEngineerRouteImport } from './routes/roadmap.cyber-security-engineer'
import { Route as RoadmapCloudDevopsEngineerRouteImport } from './routes/roadmap.cloud-devops-engineer'
import { Route as RoadmapAiEngineerRouteImport } from './routes/roadmap.ai-engineer'
import { Route as TrackSystemDesignVideosRouteImport } from './routes/track.system-design.videos'
import { Route as TrackSystemDesignPracticeRouteImport } from './routes/track.system-design.practice'
import { Route as TrackSystemDesignNotesRouteImport } from './routes/track.system-design.notes'
import { Route as TrackMathVideosRouteImport } from './routes/track.math.videos'
import { Route as TrackMathPracticeRouteImport } from './routes/track.math.practice'
import { Route as TrackMathNotesRouteImport } from './routes/track.math.notes'
import { Route as TrackGitLinuxVideosRouteImport } from './routes/track.git-linux.videos'
import { Route as TrackGitLinuxPracticeRouteImport } from './routes/track.git-linux.practice'
import { Route as TrackGitLinuxNotesRouteImport } from './routes/track.git-linux.notes'
import { Route as TrackFullstackVideosRouteImport } from './routes/track.fullstack.videos'
import { Route as TrackFullstackPracticeRouteImport } from './routes/track.fullstack.practice'
import { Route as TrackFullstackNotesRouteImport } from './routes/track.fullstack.notes'
import { Route as TrackDsaVideosRouteImport } from './routes/track.dsa.videos'
import { Route as TrackDsaPracticeRouteImport } from './routes/track.dsa.practice'
import { Route as TrackDsaNotesRouteImport } from './routes/track.dsa.notes'
import { Route as TrackDataScienceVideosRouteImport } from './routes/track.data-science.videos'
import { Route as TrackDataSciencePracticeRouteImport } from './routes/track.data-science.practice'
import { Route as TrackDataScienceNotesRouteImport } from './routes/track.data-science.notes'
import { Route as TrackCoreCsVideosRouteImport } from './routes/track.core-cs.videos'
import { Route as TrackCoreCsPracticeRouteImport } from './routes/track.core-cs.practice'
import { Route as TrackCoreCsNotesRouteImport } from './routes/track.core-cs.notes'
import { Route as TrackCloudDevopsVideosRouteImport } from './routes/track.cloud-devops.videos'
import { Route as TrackCloudDevopsPracticeRouteImport } from './routes/track.cloud-devops.practice'
import { Route as TrackCloudDevopsNotesRouteImport } from './routes/track.cloud-devops.notes'
import { Route as TrackAptitudeVideosRouteImport } from './routes/track.aptitude.videos'
import { Route as TrackAptitudePracticeRouteImport } from './routes/track.aptitude.practice'
import { Route as TrackAptitudeNotesRouteImport } from './routes/track.aptitude.notes'
import { Route as TrackAiMlVideosRouteImport } from './routes/track.ai-ml.videos'
import { Route as TrackAiMlPracticeRouteImport } from './routes/track.ai-ml.practice'
import { Route as TrackAiMlNotesRouteImport } from './routes/track.ai-ml.notes'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSlugRoute = TrackSlugRouteImport.update({
  id: '/track/$slug',
  path: '/track/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapSystemDesignEngineerRoute =
  RoadmapSystemDesignEngineerRouteImport.update({
    id: '/roadmap/system-design-engineer',
    path: '/roadmap/system-design-engineer',
    getParentRoute: () => rootRouteImport,
  } as any)
const RoadmapSdeRoute = RoadmapSdeRouteImport.update({
  id: '/roadmap/sde',
  path: '/roadmap/sde',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapMlEngineerRoute = RoadmapMlEngineerRouteImport.update({
  id: '/roadmap/ml-engineer',
  path: '/roadmap/ml-engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapFullstackDeveloperRoute =
  RoadmapFullstackDeveloperRouteImport.update({
    id: '/roadmap/fullstack-developer',
    path: '/roadmap/fullstack-developer',
    getParentRoute: () => rootRouteImport,
  } as any)
const RoadmapDataScientistRoute = RoadmapDataScientistRouteImport.update({
  id: '/roadmap/data-scientist',
  path: '/roadmap/data-scientist',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapCyberSecurityEngineerRoute =
  RoadmapCyberSecurityEngineerRouteImport.update({
    id: '/roadmap/cyber-security-engineer',
    path: '/roadmap/cyber-security-engineer',
    getParentRoute: () => rootRouteImport,
  } as any)
const RoadmapCloudDevopsEngineerRoute =
  RoadmapCloudDevopsEngineerRouteImport.update({
    id: '/roadmap/cloud-devops-engineer',
    path: '/roadmap/cloud-devops-engineer',
    getParentRoute: () => rootRouteImport,
  } as any)
const RoadmapAiEngineerRoute = RoadmapAiEngineerRouteImport.update({
  id: '/roadmap/ai-engineer',
  path: '/roadmap/ai-engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSystemDesignVideosRoute = TrackSystemDesignVideosRouteImport.update({
  id: '/track/system-design/videos',
  path: '/track/system-design/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackSystemDesignPracticeRoute =
  TrackSystemDesignPracticeRouteImport.update({
    id: '/track/system-design/practice',
    path: '/track/system-design/practice',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrackSystemDesignNotesRoute = TrackSystemDesignNotesRouteImport.update({
  id: '/track/system-design/notes',
  path: '/track/system-design/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackMathVideosRoute = TrackMathVideosRouteImport.update({
  id: '/track/math/videos',
  path: '/track/math/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackMathPracticeRoute = TrackMathPracticeRouteImport.update({
  id: '/track/math/practice',
  path: '/track/math/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackMathNotesRoute = TrackMathNotesRouteImport.update({
  id: '/track/math/notes',
  path: '/track/math/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackGitLinuxVideosRoute = TrackGitLinuxVideosRouteImport.update({
  id: '/track/git-linux/videos',
  path: '/track/git-linux/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackGitLinuxPracticeRoute = TrackGitLinuxPracticeRouteImport.update({
  id: '/track/git-linux/practice',
  path: '/track/git-linux/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackGitLinuxNotesRoute = TrackGitLinuxNotesRouteImport.update({
  id: '/track/git-linux/notes',
  path: '/track/git-linux/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackFullstackVideosRoute = TrackFullstackVideosRouteImport.update({
  id: '/track/fullstack/videos',
  path: '/track/fullstack/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackFullstackPracticeRoute = TrackFullstackPracticeRouteImport.update({
  id: '/track/fullstack/practice',
  path: '/track/fullstack/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackFullstackNotesRoute = TrackFullstackNotesRouteImport.update({
  id: '/track/fullstack/notes',
  path: '/track/fullstack/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDsaVideosRoute = TrackDsaVideosRouteImport.update({
  id: '/track/dsa/videos',
  path: '/track/dsa/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDsaPracticeRoute = TrackDsaPracticeRouteImport.update({
  id: '/track/dsa/practice',
  path: '/track/dsa/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDsaNotesRoute = TrackDsaNotesRouteImport.update({
  id: '/track/dsa/notes',
  path: '/track/dsa/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDataScienceVideosRoute = TrackDataScienceVideosRouteImport.update({
  id: '/track/data-science/videos',
  path: '/track/data-science/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackDataSciencePracticeRoute =
  TrackDataSciencePracticeRouteImport.update({
    id: '/track/data-science/practice',
    path: '/track/data-science/practice',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrackDataScienceNotesRoute = TrackDataScienceNotesRouteImport.update({
  id: '/track/data-science/notes',
  path: '/track/data-science/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCoreCsVideosRoute = TrackCoreCsVideosRouteImport.update({
  id: '/track/core-cs/videos',
  path: '/track/core-cs/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCoreCsPracticeRoute = TrackCoreCsPracticeRouteImport.update({
  id: '/track/core-cs/practice',
  path: '/track/core-cs/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCoreCsNotesRoute = TrackCoreCsNotesRouteImport.update({
  id: '/track/core-cs/notes',
  path: '/track/core-cs/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCloudDevopsVideosRoute = TrackCloudDevopsVideosRouteImport.update({
  id: '/track/cloud-devops/videos',
  path: '/track/cloud-devops/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCloudDevopsPracticeRoute =
  TrackCloudDevopsPracticeRouteImport.update({
    id: '/track/cloud-devops/practice',
    path: '/track/cloud-devops/practice',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrackCloudDevopsNotesRoute = TrackCloudDevopsNotesRouteImport.update({
  id: '/track/cloud-devops/notes',
  path: '/track/cloud-devops/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAptitudeVideosRoute = TrackAptitudeVideosRouteImport.update({
  id: '/track/aptitude/videos',
  path: '/track/aptitude/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAptitudePracticeRoute = TrackAptitudePracticeRouteImport.update({
  id: '/track/aptitude/practice',
  path: '/track/aptitude/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAptitudeNotesRoute = TrackAptitudeNotesRouteImport.update({
  id: '/track/aptitude/notes',
  path: '/track/aptitude/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAiMlVideosRoute = TrackAiMlVideosRouteImport.update({
  id: '/track/ai-ml/videos',
  path: '/track/ai-ml/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAiMlPracticeRoute = TrackAiMlPracticeRouteImport.update({
  id: '/track/ai-ml/practice',
  path: '/track/ai-ml/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackAiMlNotesRoute = TrackAiMlNotesRouteImport.update({
  id: '/track/ai-ml/notes',
  path: '/track/ai-ml/notes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/internships': typeof InternshipsRoute
  '/mentors': typeof MentorsRoute
  '/roadmaps': typeof RoadmapsRoute
  '/tutor': typeof TutorRoute
  '/roadmap/ai-engineer': typeof RoadmapAiEngineerRoute
  '/roadmap/cloud-devops-engineer': typeof RoadmapCloudDevopsEngineerRoute
  '/roadmap/cyber-security-engineer': typeof RoadmapCyberSecurityEngineerRoute
  '/roadmap/data-scientist': typeof RoadmapDataScientistRoute
  '/roadmap/fullstack-developer': typeof RoadmapFullstackDeveloperRoute
  '/roadmap/ml-engineer': typeof RoadmapMlEngineerRoute
  '/roadmap/sde': typeof RoadmapSdeRoute
  '/roadmap/system-design-engineer': typeof RoadmapSystemDesignEngineerRoute
  '/track/$slug': typeof TrackSlugRoute
  '/track/ai-ml/notes': typeof TrackAiMlNotesRoute
  '/track/ai-ml/practice': typeof TrackAiMlPracticeRoute
  '/track/ai-ml/videos': typeof TrackAiMlVideosRoute
  '/track/aptitude/notes': typeof TrackAptitudeNotesRoute
  '/track/aptitude/practice': typeof TrackAptitudePracticeRoute
  '/track/aptitude/videos': typeof TrackAptitudeVideosRoute
  '/track/cloud-devops/notes': typeof TrackCloudDevopsNotesRoute
  '/track/cloud-devops/practice': typeof TrackCloudDevopsPracticeRoute
  '/track/cloud-devops/videos': typeof TrackCloudDevopsVideosRoute
  '/track/core-cs/notes': typeof TrackCoreCsNotesRoute
  '/track/core-cs/practice': typeof TrackCoreCsPracticeRoute
  '/track/core-cs/videos': typeof TrackCoreCsVideosRoute
  '/track/data-science/notes': typeof TrackDataScienceNotesRoute
  '/track/data-science/practice': typeof TrackDataSciencePracticeRoute
  '/track/data-science/videos': typeof TrackDataScienceVideosRoute
  '/track/dsa/notes': typeof TrackDsaNotesRoute
  '/track/dsa/practice': typeof TrackDsaPracticeRoute
  '/track/dsa/videos': typeof TrackDsaVideosRoute
  '/track/fullstack/notes': typeof TrackFullstackNotesRoute
  '/track/fullstack/practice': typeof TrackFullstackPracticeRoute
  '/track/fullstack/videos': typeof TrackFullstackVideosRoute
  '/track/git-linux/notes': typeof TrackGitLinuxNotesRoute
  '/track/git-linux/practice': typeof TrackGitLinuxPracticeRoute
  '/track/git-linux/videos': typeof TrackGitLinuxVideosRoute
  '/track/math/notes': typeof TrackMathNotesRoute
  '/track/math/practice': typeof TrackMathPracticeRoute
  '/track/math/videos': typeof TrackMathVideosRoute
  '/track/system-design/notes': typeof TrackSystemDesignNotesRoute
  '/track/system-design/practice': typeof TrackSystemDesignPracticeRoute
  '/track/system-design/videos': typeof TrackSystemDesignVideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/internships': typeof InternshipsRoute
  '/mentors': typeof MentorsRoute
  '/roadmaps': typeof RoadmapsRoute
  '/tutor': typeof TutorRoute
  '/roadmap/ai-engineer': typeof RoadmapAiEngineerRoute
  '/roadmap/cloud-devops-engineer': typeof RoadmapCloudDevopsEngineerRoute
  '/roadmap/cyber-security-engineer': typeof RoadmapCyberSecurityEngineerRoute
  '/roadmap/data-scientist': typeof RoadmapDataScientistRoute
  '/roadmap/fullstack-developer': typeof RoadmapFullstackDeveloperRoute
  '/roadmap/ml-engineer': typeof RoadmapMlEngineerRoute
  '/roadmap/sde': typeof RoadmapSdeRoute
  '/roadmap/system-design-engineer': typeof RoadmapSystemDesignEngineerRoute
  '/track/$slug': typeof TrackSlugRoute
  '/track/ai-ml/notes': typeof TrackAiMlNotesRoute
  '/track/ai-ml/practice': typeof TrackAiMlPracticeRoute
  '/track/ai-ml/videos': typeof TrackAiMlVideosRoute
  '/track/aptitude/notes': typeof TrackAptitudeNotesRoute
  '/track/aptitude/practice': typeof TrackAptitudePracticeRoute
  '/track/aptitude/videos': typeof TrackAptitudeVideosRoute
  '/track/cloud-devops/notes': typeof TrackCloudDevopsNotesRoute
  '/track/cloud-devops/practice': typeof TrackCloudDevopsPracticeRoute
  '/track/cloud-devops/videos': typeof TrackCloudDevopsVideosRoute
  '/track/core-cs/notes': typeof TrackCoreCsNotesRoute
  '/track/core-cs/practice': typeof TrackCoreCsPracticeRoute
  '/track/core-cs/videos': typeof TrackCoreCsVideosRoute
  '/track/data-science/notes': typeof TrackDataScienceNotesRoute
  '/track/data-science/practice': typeof TrackDataSciencePracticeRoute
  '/track/data-science/videos': typeof TrackDataScienceVideosRoute
  '/track/dsa/notes': typeof TrackDsaNotesRoute
  '/track/dsa/practice': typeof TrackDsaPracticeRoute
  '/track/dsa/videos': typeof TrackDsaVideosRoute
  '/track/fullstack/notes': typeof TrackFullstackNotesRoute
  '/track/fullstack/practice': typeof TrackFullstackPracticeRoute
  '/track/fullstack/videos': typeof TrackFullstackVideosRoute
  '/track/git-linux/notes': typeof TrackGitLinuxNotesRoute
  '/track/git-linux/practice': typeof TrackGitLinuxPracticeRoute
  '/track/git-linux/videos': typeof TrackGitLinuxVideosRoute
  '/track/math/notes': typeof TrackMathNotesRoute
  '/track/math/practice': typeof TrackMathPracticeRoute
  '/track/math/videos': typeof TrackMathVideosRoute
  '/track/system-design/notes': typeof TrackSystemDesignNotesRoute
  '/track/system-design/practice': typeof TrackSystemDesignPracticeRoute
  '/track/system-design/videos': typeof TrackSystemDesignVideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/internships': typeof InternshipsRoute
  '/mentors': typeof MentorsRoute
  '/roadmaps': typeof RoadmapsRoute
  '/tutor': typeof TutorRoute
  '/roadmap/ai-engineer': typeof RoadmapAiEngineerRoute
  '/roadmap/cloud-devops-engineer': typeof RoadmapCloudDevopsEngineerRoute
  '/roadmap/cyber-security-engineer': typeof RoadmapCyberSecurityEngineerRoute
  '/roadmap/data-scientist': typeof RoadmapDataScientistRoute
  '/roadmap/fullstack-developer': typeof RoadmapFullstackDeveloperRoute
  '/roadmap/ml-engineer': typeof RoadmapMlEngineerRoute
  '/roadmap/sde': typeof RoadmapSdeRoute
  '/roadmap/system-design-engineer': typeof RoadmapSystemDesignEngineerRoute
  '/track/$slug': typeof TrackSlugRoute
  '/track/ai-ml/notes': typeof TrackAiMlNotesRoute
  '/track/ai-ml/practice': typeof TrackAiMlPracticeRoute
  '/track/ai-ml/videos': typeof TrackAiMlVideosRoute
  '/track/aptitude/notes': typeof TrackAptitudeNotesRoute
  '/track/aptitude/practice': typeof TrackAptitudePracticeRoute
  '/track/aptitude/videos': typeof TrackAptitudeVideosRoute
  '/track/cloud-devops/notes': typeof TrackCloudDevopsNotesRoute
  '/track/cloud-devops/practice': typeof TrackCloudDevopsPracticeRoute
  '/track/cloud-devops/videos': typeof TrackCloudDevopsVideosRoute
  '/track/core-cs/notes': typeof TrackCoreCsNotesRoute
  '/track/core-cs/practice': typeof TrackCoreCsPracticeRoute
  '/track/core-cs/videos': typeof TrackCoreCsVideosRoute
  '/track/data-science/notes': typeof TrackDataScienceNotesRoute
  '/track/data-science/practice': typeof TrackDataSciencePracticeRoute
  '/track/data-science/videos': typeof TrackDataScienceVideosRoute
  '/track/dsa/notes': typeof TrackDsaNotesRoute
  '/track/dsa/practice': typeof TrackDsaPracticeRoute
  '/track/dsa/videos': typeof TrackDsaVideosRoute
  '/track/fullstack/notes': typeof TrackFullstackNotesRoute
  '/track/fullstack/practice': typeof TrackFullstackPracticeRoute
  '/track/fullstack/videos': typeof TrackFullstackVideosRoute
  '/track/git-linux/notes': typeof TrackGitLinuxNotesRoute
  '/track/git-linux/practice': typeof TrackGitLinuxPracticeRoute
  '/track/git-linux/videos': typeof TrackGitLinuxVideosRoute
  '/track/math/notes': typeof TrackMathNotesRoute
  '/track/math/practice': typeof TrackMathPracticeRoute
  '/track/math/videos': typeof TrackMathVideosRoute
  '/track/system-design/notes': typeof TrackSystemDesignNotesRoute
  '/track/system-design/practice': typeof TrackSystemDesignPracticeRoute
  '/track/system-design/videos': typeof TrackSystemDesignVideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community'
    | '/internships'
    | '/mentors'
    | '/roadmaps'
    | '/tutor'
    | '/roadmap/ai-engineer'
    | '/roadmap/cloud-devops-engineer'
    | '/roadmap/cyber-security-engineer'
    | '/roadmap/data-scientist'
    | '/roadmap/fullstack-developer'
    | '/roadmap/ml-engineer'
    | '/roadmap/sde'
    | '/roadmap/system-design-engineer'
    | '/track/$slug'
    | '/track/ai-ml/notes'
    | '/track/ai-ml/practice'
    | '/track/ai-ml/videos'
    | '/track/aptitude/notes'
    | '/track/aptitude/practice'
    | '/track/aptitude/videos'
    | '/track/cloud-devops/notes'
    | '/track/cloud-devops/practice'
    | '/track/cloud-devops/videos'
    | '/track/core-cs/notes'
    | '/track/core-cs/practice'
    | '/track/core-cs/videos'
    | '/track/data-science/notes'
    | '/track/data-science/practice'
    | '/track/data-science/videos'
    | '/track/dsa/notes'
    | '/track/dsa/practice'
    | '/track/dsa/videos'
    | '/track/fullstack/notes'
    | '/track/fullstack/practice'
    | '/track/fullstack/videos'
    | '/track/git-linux/notes'
    | '/track/git-linux/practice'
    | '/track/git-linux/videos'
    | '/track/math/notes'
    | '/track/math/practice'
    | '/track/math/videos'
    | '/track/system-design/notes'
    | '/track/system-design/practice'
    | '/track/system-design/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/internships'
    | '/mentors'
    | '/roadmaps'
    | '/tutor'
    | '/roadmap/ai-engineer'
    | '/roadmap/cloud-devops-engineer'
    | '/roadmap/cyber-security-engineer'
    | '/roadmap/data-scientist'
    | '/roadmap/fullstack-developer'
    | '/roadmap/ml-engineer'
    | '/roadmap/sde'
    | '/roadmap/system-design-engineer'
    | '/track/$slug'
    | '/track/ai-ml/notes'
    | '/track/ai-ml/practice'
    | '/track/ai-ml/videos'
    | '/track/aptitude/notes'
    | '/track/aptitude/practice'
    | '/track/aptitude/videos'
    | '/track/cloud-devops/notes'
    | '/track/cloud-devops/practice'
    | '/track/cloud-devops/videos'
    | '/track/core-cs/notes'
    | '/track/core-cs/practice'
    | '/track/core-cs/videos'
    | '/track/data-science/notes'
    | '/track/data-science/practice'
    | '/track/data-science/videos'
    | '/track/dsa/notes'
    | '/track/dsa/practice'
    | '/track/dsa/videos'
    | '/track/fullstack/notes'
    | '/track/fullstack/practice'
    | '/track/fullstack/videos'
    | '/track/git-linux/notes'
    | '/track/git-linux/practice'
    | '/track/git-linux/videos'
    | '/track/math/notes'
    | '/track/math/practice'
    | '/track/math/videos'
    | '/track/system-design/notes'
    | '/track/system-design/practice'
    | '/track/system-design/videos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/community'
    | '/internships'
    | '/mentors'
    | '/roadmaps'
    | '/tutor'
    | '/roadmap/ai-engineer'
    | '/roadmap/cloud-devops-engineer'
    | '/roadmap/cyber-security-engineer'
    | '/roadmap/data-scientist'
    | '/roadmap/fullstack-developer'
    | '/roadmap/ml-engineer'
    | '/roadmap/sde'
    | '/roadmap/system-design-engineer'
    | '/track/$slug'
    | '/track/ai-ml/notes'
    | '/track/ai-ml/practice'
    | '/track/ai-ml/videos'
    | '/track/aptitude/notes'
    | '/track/aptitude/practice'
    | '/track/aptitude/videos'
    | '/track/cloud-devops/notes'
    | '/track/cloud-devops/practice'
    | '/track/cloud-devops/videos'
    | '/track/core-cs/notes'
    | '/track/core-cs/practice'
    | '/track/core-cs/videos'
    | '/track/data-science/notes'
    | '/track/data-science/practice'
    | '/track/data-science/videos'
    | '/track/dsa/notes'
    | '/track/dsa/practice'
    | '/track/dsa/videos'
    | '/track/fullstack/notes'
    | '/track/fullstack/practice'
    | '/track/fullstack/videos'
    | '/track/git-linux/notes'
    | '/track/git-linux/practice'
    | '/track/git-linux/videos'
    | '/track/math/notes'
    | '/track/math/practice'
    | '/track/math/videos'
    | '/track/system-design/notes'
    | '/track/system-design/practice'
    | '/track/system-design/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  InternshipsRoute: typeof InternshipsRoute
  MentorsRoute: typeof MentorsRoute
  RoadmapsRoute: typeof RoadmapsRoute
  TutorRoute: typeof TutorRoute
  RoadmapAiEngineerRoute: typeof RoadmapAiEngineerRoute
  RoadmapCloudDevopsEngineerRoute: typeof RoadmapCloudDevopsEngineerRoute
  RoadmapCyberSecurityEngineerRoute: typeof RoadmapCyberSecurityEngineerRoute
  RoadmapDataScientistRoute: typeof RoadmapDataScientistRoute
  RoadmapFullstackDeveloperRoute: typeof RoadmapFullstackDeveloperRoute
  RoadmapMlEngineerRoute: typeof RoadmapMlEngineerRoute
  RoadmapSdeRoute: typeof RoadmapSdeRoute
  RoadmapSystemDesignEngineerRoute: typeof RoadmapSystemDesignEngineerRoute
  TrackSlugRoute: typeof TrackSlugRoute
  TrackAiMlNotesRoute: typeof TrackAiMlNotesRoute
  TrackAiMlPracticeRoute: typeof TrackAiMlPracticeRoute
  TrackAiMlVideosRoute: typeof TrackAiMlVideosRoute
  TrackAptitudeNotesRoute: typeof TrackAptitudeNotesRoute
  TrackAptitudePracticeRoute: typeof TrackAptitudePracticeRoute
  TrackAptitudeVideosRoute: typeof TrackAptitudeVideosRoute
  TrackCloudDevopsNotesRoute: typeof TrackCloudDevopsNotesRoute
  TrackCloudDevopsPracticeRoute: typeof TrackCloudDevopsPracticeRoute
  TrackCloudDevopsVideosRoute: typeof TrackCloudDevopsVideosRoute
  TrackCoreCsNotesRoute: typeof TrackCoreCsNotesRoute
  TrackCoreCsPracticeRoute: typeof TrackCoreCsPracticeRoute
  TrackCoreCsVideosRoute: typeof TrackCoreCsVideosRoute
  TrackDataScienceNotesRoute: typeof TrackDataScienceNotesRoute
  TrackDataSciencePracticeRoute: typeof TrackDataSciencePracticeRoute
  TrackDataScienceVideosRoute: typeof TrackDataScienceVideosRoute
  TrackDsaNotesRoute: typeof TrackDsaNotesRoute
  TrackDsaPracticeRoute: typeof TrackDsaPracticeRoute
  TrackDsaVideosRoute: typeof TrackDsaVideosRoute
  TrackFullstackNotesRoute: typeof TrackFullstackNotesRoute
  TrackFullstackPracticeRoute: typeof TrackFullstackPracticeRoute
  TrackFullstackVideosRoute: typeof TrackFullstackVideosRoute
  TrackGitLinuxNotesRoute: typeof TrackGitLinuxNotesRoute
  TrackGitLinuxPracticeRoute: typeof TrackGitLinuxPracticeRoute
  TrackGitLinuxVideosRoute: typeof TrackGitLinuxVideosRoute
  TrackMathNotesRoute: typeof TrackMathNotesRoute
  TrackMathPracticeRoute: typeof TrackMathPracticeRoute
  TrackMathVideosRoute: typeof TrackMathVideosRoute
  TrackSystemDesignNotesRoute: typeof TrackSystemDesignNotesRoute
  TrackSystemDesignPracticeRoute: typeof TrackSystemDesignPracticeRoute
  TrackSystemDesignVideosRoute: typeof TrackSystemDesignVideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$slug': {
      id: '/track/$slug'
      path: '/track/$slug'
      fullPath: '/track/$slug'
      preLoaderRoute: typeof TrackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/system-design-engineer': {
      id: '/roadmap/system-design-engineer'
      path: '/roadmap/system-design-engineer'
      fullPath: '/roadmap/system-design-engineer'
      preLoaderRoute: typeof RoadmapSystemDesignEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/sde': {
      id: '/roadmap/sde'
      path: '/roadmap/sde'
      fullPath: '/roadmap/sde'
      preLoaderRoute: typeof RoadmapSdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/ml-engineer': {
      id: '/roadmap/ml-engineer'
      path: '/roadmap/ml-engineer'
      fullPath: '/roadmap/ml-engineer'
      preLoaderRoute: typeof RoadmapMlEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/fullstack-developer': {
      id: '/roadmap/fullstack-developer'
      path: '/roadmap/fullstack-developer'
      fullPath: '/roadmap/fullstack-developer'
      preLoaderRoute: typeof RoadmapFullstackDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/data-scientist': {
      id: '/roadmap/data-scientist'
      path: '/roadmap/data-scientist'
      fullPath: '/roadmap/data-scientist'
      preLoaderRoute: typeof RoadmapDataScientistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/cyber-security-engineer': {
      id: '/roadmap/cyber-security-engineer'
      path: '/roadmap/cyber-security-engineer'
      fullPath: '/roadmap/cyber-security-engineer'
      preLoaderRoute: typeof RoadmapCyberSecurityEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/cloud-devops-engineer': {
      id: '/roadmap/cloud-devops-engineer'
      path: '/roadmap/cloud-devops-engineer'
      fullPath: '/roadmap/cloud-devops-engineer'
      preLoaderRoute: typeof RoadmapCloudDevopsEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/ai-engineer': {
      id: '/roadmap/ai-engineer'
      path: '/roadmap/ai-engineer'
      fullPath: '/roadmap/ai-engineer'
      preLoaderRoute: typeof RoadmapAiEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/system-design/videos': {
      id: '/track/system-design/videos'
      path: '/track/system-design/videos'
      fullPath: '/track/system-design/videos'
      preLoaderRoute: typeof TrackSystemDesignVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/system-design/practice': {
      id: '/track/system-design/practice'
      path: '/track/system-design/practice'
      fullPath: '/track/system-design/practice'
      preLoaderRoute: typeof TrackSystemDesignPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/system-design/notes': {
      id: '/track/system-design/notes'
      path: '/track/system-design/notes'
      fullPath: '/track/system-design/notes'
      preLoaderRoute: typeof TrackSystemDesignNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/math/videos': {
      id: '/track/math/videos'
      path: '/track/math/videos'
      fullPath: '/track/math/videos'
      preLoaderRoute: typeof TrackMathVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/math/practice': {
      id: '/track/math/practice'
      path: '/track/math/practice'
      fullPath: '/track/math/practice'
      preLoaderRoute: typeof TrackMathPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/math/notes': {
      id: '/track/math/notes'
      path: '/track/math/notes'
      fullPath: '/track/math/notes'
      preLoaderRoute: typeof TrackMathNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/git-linux/videos': {
      id: '/track/git-linux/videos'
      path: '/track/git-linux/videos'
      fullPath: '/track/git-linux/videos'
      preLoaderRoute: typeof TrackGitLinuxVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/git-linux/practice': {
      id: '/track/git-linux/practice'
      path: '/track/git-linux/practice'
      fullPath: '/track/git-linux/practice'
      preLoaderRoute: typeof TrackGitLinuxPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/git-linux/notes': {
      id: '/track/git-linux/notes'
      path: '/track/git-linux/notes'
      fullPath: '/track/git-linux/notes'
      preLoaderRoute: typeof TrackGitLinuxNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/fullstack/videos': {
      id: '/track/fullstack/videos'
      path: '/track/fullstack/videos'
      fullPath: '/track/fullstack/videos'
      preLoaderRoute: typeof TrackFullstackVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/fullstack/practice': {
      id: '/track/fullstack/practice'
      path: '/track/fullstack/practice'
      fullPath: '/track/fullstack/practice'
      preLoaderRoute: typeof TrackFullstackPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/fullstack/notes': {
      id: '/track/fullstack/notes'
      path: '/track/fullstack/notes'
      fullPath: '/track/fullstack/notes'
      preLoaderRoute: typeof TrackFullstackNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/dsa/videos': {
      id: '/track/dsa/videos'
      path: '/track/dsa/videos'
      fullPath: '/track/dsa/videos'
      preLoaderRoute: typeof TrackDsaVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/dsa/practice': {
      id: '/track/dsa/practice'
      path: '/track/dsa/practice'
      fullPath: '/track/dsa/practice'
      preLoaderRoute: typeof TrackDsaPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/dsa/notes': {
      id: '/track/dsa/notes'
      path: '/track/dsa/notes'
      fullPath: '/track/dsa/notes'
      preLoaderRoute: typeof TrackDsaNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/data-science/videos': {
      id: '/track/data-science/videos'
      path: '/track/data-science/videos'
      fullPath: '/track/data-science/videos'
      preLoaderRoute: typeof TrackDataScienceVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/data-science/practice': {
      id: '/track/data-science/practice'
      path: '/track/data-science/practice'
      fullPath: '/track/data-science/practice'
      preLoaderRoute: typeof TrackDataSciencePracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/data-science/notes': {
      id: '/track/data-science/notes'
      path: '/track/data-science/notes'
      fullPath: '/track/data-science/notes'
      preLoaderRoute: typeof TrackDataScienceNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/core-cs/videos': {
      id: '/track/core-cs/videos'
      path: '/track/core-cs/videos'
      fullPath: '/track/core-cs/videos'
      preLoaderRoute: typeof TrackCoreCsVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/core-cs/practice': {
      id: '/track/core-cs/practice'
      path: '/track/core-cs/practice'
      fullPath: '/track/core-cs/practice'
      preLoaderRoute: typeof TrackCoreCsPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/core-cs/notes': {
      id: '/track/core-cs/notes'
      path: '/track/core-cs/notes'
      fullPath: '/track/core-cs/notes'
      preLoaderRoute: typeof TrackCoreCsNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/cloud-devops/videos': {
      id: '/track/cloud-devops/videos'
      path: '/track/cloud-devops/videos'
      fullPath: '/track/cloud-devops/videos'
      preLoaderRoute: typeof TrackCloudDevopsVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/cloud-devops/practice': {
      id: '/track/cloud-devops/practice'
      path: '/track/cloud-devops/practice'
      fullPath: '/track/cloud-devops/practice'
      preLoaderRoute: typeof TrackCloudDevopsPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/cloud-devops/notes': {
      id: '/track/cloud-devops/notes'
      path: '/track/cloud-devops/notes'
      fullPath: '/track/cloud-devops/notes'
      preLoaderRoute: typeof TrackCloudDevopsNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/aptitude/videos': {
      id: '/track/aptitude/videos'
      path: '/track/aptitude/videos'
      fullPath: '/track/aptitude/videos'
      preLoaderRoute: typeof TrackAptitudeVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/aptitude/practice': {
      id: '/track/aptitude/practice'
      path: '/track/aptitude/practice'
      fullPath: '/track/aptitude/practice'
      preLoaderRoute: typeof TrackAptitudePracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/aptitude/notes': {
      id: '/track/aptitude/notes'
      path: '/track/aptitude/notes'
      fullPath: '/track/aptitude/notes'
      preLoaderRoute: typeof TrackAptitudeNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/ai-ml/videos': {
      id: '/track/ai-ml/videos'
      path: '/track/ai-ml/videos'
      fullPath: '/track/ai-ml/videos'
      preLoaderRoute: typeof TrackAiMlVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/ai-ml/practice': {
      id: '/track/ai-ml/practice'
      path: '/track/ai-ml/practice'
      fullPath: '/track/ai-ml/practice'
      preLoaderRoute: typeof TrackAiMlPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/ai-ml/notes': {
      id: '/track/ai-ml/notes'
      path: '/track/ai-ml/notes'
      fullPath: '/track/ai-ml/notes'
      preLoaderRoute: typeof TrackAiMlNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  InternshipsRoute: InternshipsRoute,
  MentorsRoute: MentorsRoute,
  RoadmapsRoute: RoadmapsRoute,
  TutorRoute: TutorRoute,
  RoadmapAiEngineerRoute: RoadmapAiEngineerRoute,
  RoadmapCloudDevopsEngineerRoute: RoadmapCloudDevopsEngineerRoute,
  RoadmapCyberSecurityEngineerRoute: RoadmapCyberSecurityEngineerRoute,
  RoadmapDataScientistRoute: RoadmapDataScientistRoute,
  RoadmapFullstackDeveloperRoute: RoadmapFullstackDeveloperRoute,
  RoadmapMlEngineerRoute: RoadmapMlEngineerRoute,
  RoadmapSdeRoute: RoadmapSdeRoute,
  RoadmapSystemDesignEngineerRoute: RoadmapSystemDesignEngineerRoute,
  TrackSlugRoute: TrackSlugRoute,
  TrackAiMlNotesRoute: TrackAiMlNotesRoute,
  TrackAiMlPracticeRoute: TrackAiMlPracticeRoute,
  TrackAiMlVideosRoute: TrackAiMlVideosRoute,
  TrackAptitudeNotesRoute: TrackAptitudeNotesRoute,
  TrackAptitudePracticeRoute: TrackAptitudePracticeRoute,
  TrackAptitudeVideosRoute: TrackAptitudeVideosRoute,
  TrackCloudDevopsNotesRoute: TrackCloudDevopsNotesRoute,
  TrackCloudDevopsPracticeRoute: TrackCloudDevopsPracticeRoute,
  TrackCloudDevopsVideosRoute: TrackCloudDevopsVideosRoute,
  TrackCoreCsNotesRoute: TrackCoreCsNotesRoute,
  TrackCoreCsPracticeRoute: TrackCoreCsPracticeRoute,
  TrackCoreCsVideosRoute: TrackCoreCsVideosRoute,
  TrackDataScienceNotesRoute: TrackDataScienceNotesRoute,
  TrackDataSciencePracticeRoute: TrackDataSciencePracticeRoute,
  TrackDataScienceVideosRoute: TrackDataScienceVideosRoute,
  TrackDsaNotesRoute: TrackDsaNotesRoute,
  TrackDsaPracticeRoute: TrackDsaPracticeRoute,
  TrackDsaVideosRoute: TrackDsaVideosRoute,
  TrackFullstackNotesRoute: TrackFullstackNotesRoute,
  TrackFullstackPracticeRoute: TrackFullstackPracticeRoute,
  TrackFullstackVideosRoute: TrackFullstackVideosRoute,
  TrackGitLinuxNotesRoute: TrackGitLinuxNotesRoute,
  TrackGitLinuxPracticeRoute: TrackGitLinuxPracticeRoute,
  TrackGitLinuxVideosRoute: TrackGitLinuxVideosRoute,
  TrackMathNotesRoute: TrackMathNotesRoute,
  TrackMathPracticeRoute: TrackMathPracticeRoute,
  TrackMathVideosRoute: TrackMathVideosRoute,
  TrackSystemDesignNotesRoute: TrackSystemDesignNotesRoute,
  TrackSystemDesignPracticeRoute: TrackSystemDesignPracticeRoute,
  TrackSystemDesignVideosRoute: TrackSystemDesignVideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
